CREATE TABLE venues (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255),
                        city VARCHAR(255),
                        address VARCHAR(255)
);

CREATE TABLE events (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255) NOT NULL,
                        category VARCHAR(255) NOT NULL,
                        start_date DATE NOT NULL,
                        venue_id BIGINT NOT NULL
);